### ISSUE TITLE
Distribution around deployment point is not configurable

### ISSUE THREAD

**Issue by sea-bass** [mrsonandrade/pyswarming#1]
I was confused by the initial example that setting `deployment_point=[0.0, 0.0]` automatically adds a uniform distribution of +/- 5.0 meters around those coordinates, plus an orientation in the full range of 0 to 2*pi radians.

Looking at the source code, I see that `Swarm._create_robots()` simply hard-codes these parameters.

As such, I would suggest the following:
* [MUST HAVE] Allow users to configure the bounds of the X/Y position and angle
* [NICE TO HAVE] Allow users to switch between uniform distribution, Gaussian distribution, no distribution, or a list of starting poses

https://github.com/openjournals/joss-reviews/issues/5647

**Comment by mrsonandrade** [comment]
Great suggestions!
I have done both:
- Allow users to configure the bounds of the X/Y position and angle;
- Allow users to switch between uniform distribution, Gaussian distribution, no distribution, or a list of starting poses.

**Comment by sea-bass** [comment]
Awesome, thanks for adding this!
